phpcr_factories:
    jackalope.jackrabbit:
        class: '\Jackalope\RepositoryFactoryJackrabbit'
        parameters:
            - jackalope.jackrabbit_uri
            - credentials.username
            - credentials.password
        support:
            - workspace.create
